version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
assignees:
      - "ThatFrogDev"
    
