[package]
name = "notabena"
version = "0.2.0"
edition = "2021"
authors = [ "ThatFrogDev" ]
license-file = "LICENSE.md"
description = "A note-taking app for the command line. GUI support will be added (see README)."
homepage = "https://github.com/thatfrogdev/notabena"
repository = "https://github.com/thatfrogdev/notabena"
readme = "README.md"
keywords = [ "notes", "cli", "gui", "markdown" ]
categories = [ "command-line-utilities", "gui", "text-processing" ]

[dependencies]
async-std = "1.12.0"
directories = "5.0.1"
chrono = "0.4.37"
dialoguer = "0.11.0"
crossterm = "0.27.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
termimad = "0.29.1"
tempfile = "3.10.0"
